### ISSUE TITLE
Name conflict

### ISSUE THREAD

**Issue by PeteMaclean** [sivsushruth/ExBridge#1]
I have a product of about 15 years standing named ExBridge (see http://www.maclean.com/exbridge.php).  My ExBridge is a utility for migrating email from IMAP servers into Microsoft Outlook and Exchange.  I think there should be no conflict or confusion with your project but may I ask you please to consider changing the name of yours.

**Comment by sivsushruth** [comment]
@PeteMaclean  thank you for bringing to my notice. I was unaware of your work. I have not published the library yet, and will change it in the next few days. Apologies for causing you trouble.

**Comment by PeteMaclean** [comment]
Thank you very much for your graciousness in doing
this.
Pete Maclean
At 10:07 AM 8/31/2016, Sushruth Sivaramakrishnan wrote:

@PeteMaclean thank you
bringing to my notice. I was unaware of your work. I have not published
the library yet, and will change it in the next few days. Apologies for
causing you trouble. 
�
You are receiving this because you were mentioned.
Reply to this email directly,

view it on GitHub, or

mute the thread.

**Comment by sivsushruth** [comment]
@PeteMaclean This commit takes care of the issue, https://github.com/sivsushruth/ExConnect/commit/3a5c15684c5fbcfdbf51cafdec0c0329567f80dc 
I have also renamed the repo. Thank you for your patience.
